name: Basic Workflow  # The name of the workflow, which appears in the GitHub Actions UI.

on: workflow_dispatch  # This defines the event that triggers the workflow. "workflow_dispatch" allows manual triggering.

jobs:
  basic-workflow:  # Defines a job named "basic-workflow".

    runs-on: ubuntu-latest  # Specifies that this job should run on the latest Ubuntu environment.

    steps:

      - run: |
          echo "hi there"